name: Build Application

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Prevent CMake from using cached paths
      CMAKE_DISABLE_PRECOMPILE_HEADERS: ON
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libboost-system-dev libncurses5-dev libyaml-cpp-dev
        
        # Optional: Install backward-cpp for stack traces
        # sudo apt-get install -y libdw-dev

    - name: Clean and Configure CMake
      run: |
        # Remove any previous build artifacts or cache
        rm -rf build CMakeCache.txt CMakeFiles
        find . -name "*.cmake" -type f -not -path "./build/*" -delete || true
        
        # Create fresh build directory
        mkdir -p build
        cd build
        
        # Configure with clean state
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. || (echo "CMake configuration failed"; cat CMakeFiles/CMakeError.log; exit 1)

    - name: Build
      run: |
        cd build
        make -j$(nproc) VERBOSE=1 || (echo "Build failed"; exit 1)
    
    - name: Test build artifacts
      run: |
        ls -la build/
        if [ -f build/arm-teleop-direct ]; then
          echo "Build successful!"
        else
          echo "Executable not found"
          exit 1
        fi